name: Changesets
on:
  push:
    branches:
      - main
    paths:
      - 'packages/**'
env:
  CI: true
  PNPM_CACHE_FOLDER: .pnpm-store
jobs:
  version:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: checkout code repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: setup node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.17.0

      - name: install pnpm
        run: npm i pnpm@latest -g

      - name: install dependencies
        run: pnpm install

      - name: build
        run: pnpm package build

      - name: Creating .npmrc
        run: |
          cat << EOF > "$HOME/.npmrc"
            //registry.npmjs.org/:_authToken=$NPM_TOKEN
          EOF
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: create and publish versions
        uses: changesets/action@v1
        with:
          createGithubReleases: false
          publish: pnpm ci:publish
          version: pnpm ci:version
          commit: '✈️ Publish maplestory-open-api-js'
          title: '✈️ Publish maplestory-open-api-js'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
